import { Contact } from './columns'

export const contacts: Contact[] = [
  {
    id: 1,
    rank: 'Đại tá',
    position: 'Tư lệnh',
    manager: 'Đ/c Nguyễn Văn A',
    department: '',
    location: 'Bộ Tư Lệnh Thành Phố',
    militaryPostalCode: '123456',
    mobile: '0987 654 321',
  },
  {
    id: 2,
    rank: 'Thiếu tướng',
    position: 'Chính ủy',
    manager: 'Đ/c Phan Văn B',
    department: '',
    location: 'Bộ Tư Lệnh Thành Phố',
    militaryPostalCode: '654321',
    mobile: '0912 345 678',
  },
  {
    id: 3,
    rank: 'Thượng tá',
    position: '',
    manager: 'Đ/c Nguyễn Trung C',
    department: 'Ban Tác huấn',
    location: 'Phòng Tham Mưu',
    militaryPostalCode: '987654',
    mobile: '0903 456 789',
  },
  {
    id: 4,
    rank: 'Đại úy',
    position: 'Trường bắn Phú Mỹ Hưng',
    manager: 'Nguyễn Thanh Trọng',
    department: 'Ban Tác huấn',
    location: 'Phòng Tham Mưu',
    militaryPostalCode: '456789',
    mobile: '0923 567 890',
  },
  {
    id: 5,
    rank: 'Trung tá',
    position: 'Chủ nhiệm',
    manager: 'Đ/c Trần Văn D',
    department: '',
    location: 'Phòng Chính Trị',
    militaryPostalCode: '789123',
    mobile: '0965 678 901',
  },
  {
    id: 6,
    rank: 'Thiếu tá',
    position: 'Phó chủ nhiệm',
    manager: 'Đ/c Lê Văn E',
    department: '',
    location: 'Phòng Chính Trị',
    militaryPostalCode: '321789',
    mobile: '0932 789 012',
  },
  {
    id: 7,
    rank: 'Thượng úy',
    position: 'Trợ lý tuyên huấn',
    manager: 'Đ/c Phạm Thị F',
    department: 'Ban Tuyên huấn',
    location: 'Phòng Chính Trị',
    militaryPostalCode: '159753',
    mobile: '0976 123 456',
  },
  {
    id: 8,
    rank: 'Trung úy',
    position: 'Trợ lý tổ chức',
    manager: 'Đ/c Vũ Minh G',
    department: 'Ban Tổ chức',
    location: 'Phòng Chính Trị',
    militaryPostalCode: '258456',
    mobile: '0945 678 234',
  },
  {
    id: 9,
    rank: 'Đại tá',
    position: 'Trưởng phòng',
    manager: 'Đ/c Hoàng Văn H',
    department: '',
    location: 'Phòng Hậu Cần',
    militaryPostalCode: '147258',
    mobile: '0901 234 567',
  },
  {
    id: 10,
    rank: 'Thiếu tướng',
    position: 'Phó Tư lệnh',
    manager: 'Đ/c Nguyễn Thị I',
    department: '',
    location: 'Bộ Tư Lệnh Thành Phố',
    militaryPostalCode: '963852',
    mobile: '0981 345 210',
  },
  {
    id: 11,
    rank: 'Thượng tá',
    position: 'Trưởng ban Tác chiến',
    manager: 'Đ/c Đặng Văn K',
    department: 'Ban Tác huấn',
    location: 'Phòng Tham Mưu',
    militaryPostalCode: '357951',
    mobile: '0910 876 543',
  },
  {
    id: 12,
    rank: 'Trung tá',
    position: 'Trưởng ban Quân lực',
    manager: 'Đ/c Trần Hữu L',
    department: 'Ban Quân lực',
    location: 'Phòng Tham Mưu',
    militaryPostalCode: '741852',
    mobile: '0921 987 654',
  },
  {
    id: 13,
    rank: 'Đại úy',
    position: 'Trợ lý quân huấn',
    manager: 'Đ/c Lưu Văn M',
    department: 'Ban Quân huấn',
    location: 'Phòng Tham Mưu',
    militaryPostalCode: '789456',
    mobile: '0904 321 987',
  },
  {
    id: 14,
    rank: 'Thiếu tá',
    position: 'Phó trưởng ban Kế hoạch',
    manager: 'Đ/c Bùi Minh N',
    department: 'Ban Kế hoạch',
    location: 'Phòng Hậu Cần',
    militaryPostalCode: '951357',
    mobile: '0956 654 321',
  },
  {
    id: 15,
    rank: 'Trung úy',
    position: 'Trợ lý Tài chính',
    manager: 'Đ/c Hà Thị O',
    department: 'Ban Tài chính',
    location: 'Phòng Hậu Cần',
    militaryPostalCode: '654987',
    mobile: '0933 222 111',
  },
]
